# Site settings
title: HackcessibleMap - DSSG Sidewalk Team 2015
email: yunhao.lucky@gmail.com
description: "Best Routing Application for people with limited mobilities in Seattle"
#baseurl: "http://uwescience.github.io/DSSG2015"
baseurl: "http://yunhaolucky.github.io/DSSG_sidewalk"
#url: "http://uwescience.github.io/DSSG2015" 
url: "http://yunhaolucky.github.io/DSSG_sidewalk"
twitter_username: yunhaolucky 
github_username:  yunhaolucky

# Build settings
markdown: kramdown
